import Head from "next/head";
import Image from "next/image";
import Card from "../components/Card/Card";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <span className="text-blue-500 text-xl font-bold">
          Next Js Tutorial
        </span>
      </main>

      <Card />

      <div className="flex bg-green-200 w-full justify-around">
        <span className="p-4 text-blue-500">Text One</span>
        <span className="p-4 text-red-500">Text Two</span>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
